-- phpMyAdmin SQL Dump
-- version 4.7.4
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Apr 01, 2018 at 06:50 PM
-- Server version: 10.1.30-MariaDB
-- PHP Version: 7.2.1

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `tintuctt`
--

-- --------------------------------------------------------

--
-- Table structure for table `baiviet`
--

CREATE TABLE `baiviet` (
  `id` int(10) UNSIGNED NOT NULL,
  `anh` varchar(200) COLLATE utf8_unicode_ci NOT NULL,
  `tieude` varchar(200) COLLATE utf8_unicode_ci NOT NULL,
  `noidung` text COLLATE utf8_unicode_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
-- Dumping data for table `baiviet`
--

INSERT INTO `baiviet` (`id`, `anh`, `tieude`, `noidung`) VALUES
(1, 'https://media.thethao247.vn/upload/vuongnh/2018/03/31/doi-bong-han-quoc-duoc-gdkt-hagl-chi-giao-tai-pleiku1522499813.jpg', 'Đội bóng Hàn Quốc được GĐKT HAGL \'chỉ giáo\' tại Pleiku', 'Giám đốc kỹ thuật CLB HAGL, ông Chung Hae Seong cũng đến sân Pleiku theo dõi các cầu thủ trẻ FC Seoul thi đấu. Sau thành tích đoạt ngôi á quân vì trận thua phút chót trước đối thủ cạnh tranh số 1 là U.19 tuyển chọn Việt Nam, các cầu thủ U.19 FC Seoul đã nhận nhiều lời tư vấn từ ông Chung Hae Seong.\r\n\r\nTheo HLV Myung Jinyoung: “Những tư vấn của “thầy” Chung (Hae Seong) rất bổ ích, không chỉ cho bản thân tôi mà cho các cầu thủ trẻ của chúng tôi. Vì thế, chúng tôi trân trọng từng giây phút khi gặp thầy Chung, vì từ khi ông sang Việt Nam làm việc chúng tôi ít có cơ hội gặp nhau”.\r\n\r\nTrước khi về nước tối ngày 31.3, vào buổi sáng cùng ngày cả đội U.19 FC Seoul tranh thủ lên Trung tâm Hàm Rồng của CLB HAGL để tập luyện tiếp và chuẩn bị cho trận đấu kế tiếp tại giải K-League trẻ và dự bị vào ngày 4.4.'),
(2, 'https://media.thethao247.vn/upload/namnv/2018/03/31/xuantruong.jpg', 'Xuân Trường: \'Không có khó khăn gì khi vắng Tuấn Anh\'', 'Sau khi phục vụ ĐTQG đá vòng loại Asian Cup 2019, 5 cầu thủ của HAGL đã hội quân trở lại hôm 29/3. Phải di chuyển quãng đường khá dài, vì vậy vấn đề thể lực của những Xuân Trường, Văn Thanh... là đáng lo ngại.\r\n\r\nĐội bóng phố Núi chỉ có hai buổi tập với đầy đủ quân số chuẩn bị cho trận gặp Nam Định ở vòng 4 diễn ra ngày 1/4 tới. Phát biểu trước trận gặp tân binh V-League, Xuân Trường khẳng định có đầy đủ thể lực để có thể thi đấu trọn vẹn trận sắp tới.\"Tôi không có vấn đề gì với thể lực. Là cầu thủ chuyên nghiệp, ai cũng phải thích nghi với những việc như di chuyển, chênh lệch múi giờ. Tôi nghĩ mình có đủ thời gian hồi phục để gặp Nam Định\".\r\n\r\nỞ trận này, HAGL sẽ không có sự phục vụ của tiền vệ Tuấn Anh do chấn thương. Xuân Trường cho rằng đó không phải khó khăn với anh bởi: \"Không có khó khăn gì khi vắng Tuấn Anh. Tôi nghĩ ban huấn luyện sẽ có sự thay thế xứng đáng. Mỗi cầu thủ phải luôn luôn sẵn sàng để làm nhiệm vụ mà đội bóng đã giao phó\".\r\n\r\nHAGL chưa giành được chiến thắng nào sau hai trận đã đấu. Họ hòa Bình Dương và Hải Phòng và đang rất khát khao tìm kiếm một chiến thắng. Trận đấu này sẽ diễn ra lúc 19h00 ngày 1/4.'),
(3, 'https://media.thethao247.vn/upload/vuongnh/2018/03/31/truc-tiep-mu-vs-swansea-21h00-ngay-31-31522505953.JPG', 'Lukaku và Sanchez tỏa sáng, MU thắng dễ Swansea', 'MU được dự đoán sẽ thắng dễ trận này và thế trận trong những phút đầu cũng cho thấy điều đó. Phút thứ 5, Sanchez chuyền bóng vào cho Lukaku ở phía trong. Tiền đạo người Bỉ tung cú sút đâp chân hậu vệ đối phương, đi theo quỹ đạo khó vào thẳng khung thành của Swansea.\r\n\r\nSau khi Lukaku ghi bàn thắng đầu tiên, MU vẫn dễ dàng áp đặt thế trận lên đối thủ. Tiền đạo người Bỉ có thêm 1 cơ hội đối mặt nhưng dứt điểm không thành công ở phút thứ 11. Tuy vậy, họ vẫn sớm có bàn thắng thứ 2. Phút 20, từ một tình huống phản công, Lingard chọc khe cho Sanchez băng xuống tung ra cú sút sệt rất mạnh ghi bàn cho MU.Dẫn trước 2-0, MU dễ dàng thi triển các miếng đánh của mình. Trong hiệp 1, có khá nhiều cơ hội được tạo ra. Phút 31, Lingard tự tin đi bóng qua 3 cầu thủ áo trắng nhưng ở tình huống quyết định, tiền vệ người Anh lại đưa bóng đi chệch khung thành trong sự tiếc nuối của người hâm mộ. Sau đó, anh đưa được bóng vào lưới đối phương nhưng Lukaku đã bị thổi việt vị trước đó. Hiệp 1 kết thúc với cú sút hụt của Sanchez.\r\n\r\nTrong nửa đầu trận đấu, Swansea không một lần uy hiếp được khung thành của đội chủ nhà và sang hiệp 2 họ cũng chẳng khá hơn. Quỷ đỏ đã thi đấu chậm lại, gần như không muốn tấn công nhưng đội khách cũng chẳng thể tìm được mảnh lưới đối phương. Hai cơ hội nguy hiểm nhất của Swansea xuất phát từ lỗi của De Gea và hàng phòng ngự, nhưng thủ môn người Tây Ban Nha cũng đã hóa giải xuất sắc.\r\n\r\nThắng 2-0, MU đòi lại vị trí thứ 2 trên BXH Ngoại hạng Anh với 68 điểm.'),
(4, 'https://media.thethao247.vn/upload/namnv/2018/02/25/david.jpg', 'David De Gea lên tiếng, chốt xong chuyện tương lai', 'Lâu nay tương lai của David De Gea tại MU vốn là một dấu hỏi lớn. Kể từ lần đào thoát sang Real Madrid bất thành năm 2015, mùa chuyển nhượng nào báo giới cũng tốn rất nhiều giấy mực để nói về anh và tương lai tại Old Trafford hay Bernabeu.\r\n\r\nNgười ta từng nói rằng trong những bản hợp đồng mới nhất của De Gea với MU hồi năm 2016, có điều khoản yêu cầu MU bắt buộc phải bán De Gea với mức giá khoảng 30 triệu bảng nếu Real Madrid yêu cầu, thế nhưng đội bóng Hoàng gia Tây Ban Nha đã không thực hiện điều đó. Mới đây, thủ môn này được cho là đang đàm phán gia hạn hợp đồng với Quỷ đỏ, nếu không sẽ rời đi ngay trong hè này.Tuy nhiên, động thái mới nhất của De Gea cho thấy gần như chắc chắn cầu thủ này sẽ ở lại Old Trafford. Chia sẻ khi đang tập trung cùng ĐT Tây Ban Nha, De Gea khẳng định anh đang hạnh phúc ở nước Anh: “Tôi cảm thấy bản thân được tôn trọng rất nhiều ở Anh Quốc, điều vốn không được thể hiện rõ ràng tại đây (trên đất Tây Ban Nha). Tôi đạt được nhiều thứ ở nước Anh hơn là ở đây.\r\n\r\nMỗi khi lên tập trung cùng ĐTQG, tôi đều cảm thấy bản thân có sự yên bình nhất định. Lên tuyển luôn là một điều tốt với trạng thái của tôi.” De Gea nói.\r\n\r\nCó nhiều thông tin cho rằng trong lần đàm phán mới nhất với MU, De Gea khẳng định anh sẽ ở lại sân Old Trafford nếu nhận được mức lương 350.000 bảng/tuần. Anh đang nhận lương 180.000 bảng/tuần tại MU thời điểm hiện tại.'),
(5, 'http://image.24h.com.vn/upload/1-2018/images/2018-03-31/Chelsea-lo-ngay-ngay-dau-derby-London-Hang-thu-tan-nat-so-Harry-Kane-gettyimages-826965706-1522498682-332-width660height448.jpg', 'Chelsea lo ngay ngáy đấu derby London: Hàng thủ tan nát, sợ Harry Kane', 'Trận cầu tâm điểm của vòng 32 giải Ngoại hạng Anh cuối tuần này sẽ nằm ở cuộc đấu của nhà đương kim vô địch Chelsea và đội đương kim á quân Tottenham lúc 23h30 ngày Chủ nhật 1/4 (giờ Việt Nam).\r\n\r\nĐây là trận derby London có ý nghĩa rất lớn với cả hai đội trong nỗ lực cán đích ở top 4 đội dẫn đầu giải Ngoại hạng Anh mùa này nhằm dự vòng bảng Champions League mùa sau.Khoảng cách giữa Tottenham – đội đang đứng thứ 4 với Chelsea – đội đang xếp thứ 5 hiện là 5 điểm. Nếu “The Blues” không thể thắng khi làm khách của “người hàng xóm” ở Wembley, đoàn quân của HLV Antonio Conte sẽ bị top 4 bỏ xa hơn nữa và giấc mộng Champions League mùa sau có nguy cơ lớn tan vỡ với họ.\r\n\r\nKhó càng thêm khó với Chelsea khi theo tờ Telegraph, nhà ĐKVĐ giải Ngoại hạng Anh sẽ không để Thibaut Courtois – thủ thành số 1 của mình đấu Tottenham sắp tới do anh vẫn chưa đủ thể lực khi dính chấn thương gân kheo gặp phải từng khiến “người gác đền” người Bỉ lỡ trận gặp Leicester City ở FA Cup hôm 18/3.\r\n\r\nNếu Courtois không thể bắt chính cho Chelsea đấu Tottenham, rất có thể HLV Conte sẽ phải đặt niềm tin vào Willy Caballero – thủ môn đã 36 tuổi và vừa để lọt 5 bàn sau khi vào sân thế chỗ Sergio Romero ở trận thua thảm 1-6 của ĐT Argentina trước ĐT Tây Ban Nha cách đây 3 ngày.\r\n\r\n\r\nNgoài Courtois, Chelsea cũng đang đối mặt khó khăn khác ở hàng thủ khi 2 trung vệ David Luiz và Andreas Christensen vẫn chấn thương.\r\n\r\nViệc hàng thủ tan tác đang khiến cho “The Blues” gặp không ít khó khăn khi Tottenham là đội chơi tấn công rất tốc độ.\r\n\r\nĐặc biệt, “Gà trống thành London” rất có thể sẽ đón chào sự trở lại của “sát thủ” Harry Kane ở trận “Super Sunday” với Chelsea sắp tới.'),
(6, 'http://image.24h.com.vn/upload/1-2018/images/2018-03-31/Real-san-don-sieu-sao-Neymar-Kho-cuong-250-trieu-euro-va-hon-the-neymar1-1522489477-161-width660height371.jpg', 'Real săn siêu sao Neymar: Khó cưỡng 250 triệu euro và khủng hơn nữa', 'Sau khi Neymar dính chấn thương khá nặng và phải phẫu thuật bàn chân, Real Madrid đã có chút lấn cấn trong kế hoạch chiêu mộ siêu sao người Brazil ở hè 2018. Họ lo sợ Neymar sẽ gặp dư chấn, khó phát huy hết khả năng nếu tới sân Bernabeu. Tuy nhiên tờ Diario Gol tiết lộ, chủ tịch Perez sau khi suy nghĩ kĩ và bàn bạc với các cấp dưới, quyết định vẫn theo vụ Neymar.\"Ông trùm\" mê mẩn Neymar bao năm qua. Hè năm ngoái, Real đã cố gắng chèo kéo \"tiểu Pele\" nhưng chân sút này không được thẳng tiến tới nửa trắng thành Madrid vì điều khoản kí với Barca và cuối cùng gia nhập PSG giá 222 triệu euro. Báo chí Tây Ban Nha khẳng định, Neymar đến PSG là ngoài ý muốn, đành chấp nhận đi đường vòng lấy bàn đạp để sang Real.\r\n\r\nTrước khi chấn thương, Neymar được cho là không thật hạnh phúc ở PSG. Thất bại của đội bóng này ở Champions League trước chính Real càng khiến anh chán nản. \"Kền kền trắng\" dĩ nhiên không muốn bỏ lỡ cơ hội này và đang cử các chuyên gia âm thầm đám phán với bố Neymar. Những khoản tiền bạc lớn đã được đội bóng hoàng gia Tây Ban Nha vạch ra.\r\n\r\nTheo đó, ông Perez sẵn sàng chi 250 triệu euro là khoản phí chuyển nhượng Neymar cho PSG. Không thiếu tiền nhưng PSG khó giữ \"tiểu Pele\" vì tham vọng của siêu sao người Brazil quá lớn. Mặt khác, nhà ĐKVĐ La Liga và Champions League dự tính \"lót tay\" cho bố con Neymar tới 50 triệu euro. Năm ngoái, PSG từng dùng chiêu này, chi 36 triệu euro cho bố con Neymar.\r\n\r\nLiên quan tới Neymar, cầu thủ đắt giá nhất thế giới hoàn toàn có thể trở lại sân cỏ trong vòng từ 2 đến 3 tuần nữa. Nếu PSG vào chung kết cúp quốc gia Pháp vào ngày 8/5 thì Neymar sẵn sàng góp mặt. Đây là thông tin rất vui với CĐV PSG và đặc biệt là CĐV Brazil. Vòng chung kết World Cup 2018 cận kề và \"Selecao\" không thể sống thiếu Neymar.'),
(7, 'http://image.24h.com.vn/upload/1-2018/images/2018-03-31/Nhan-dinh-bong-da-Las-Palmas---Real-Madrid-Vang-Ronaldo-cho-song-ronaldo-isco-660-1522461029-466-width660height390.jpg', 'Las Palmas - Real Madrid: Nỗi lo virus FIFA và thiếu vắng Ronaldo', 'Real Madrid là một trong những CLB bị ảnh hưởng nhiều nhất bởi đợt tập trung ĐTQG tháng Ba. Đội bóng này có tới 20 cầu thủ được triệu tập để phục vụ quốc gia (cả ĐTQG và các đội tuyển trẻ). Đây chính là một trong những nỗi sợ hãi lớn nhất của \"Kền kền trắng\" bởi nguy cơ virus FIFA tấn công luôn hiển hiện trước mắt.Tuy nhiên, Real Madrid lần này khá may mắn bởi các cầu thủ đa phần lành lặn trở về. Isco là cầu thủ duy nhất gặp vấn đề về thể lực và được HLV Zidane cho nghỉ trong trận đấu này.\r\n\r\nNgoài ra, siêu sao Cristiano Ronaldo cùng một số trụ cột khác như Toni Kroos,Sergio Ramos, Marcelo cũng được ông thầy người Pháp \"cất\" để chuẩn bị cho trận đấu tại Champions League vào giữa tuần sau. \r\n\r\nHLV Zidane chỉ đăng ký 19 cầu thủ cho trận đấu này và trong đó có tới 3 thủ môn. Trên hàng công, bộ đôi Gareth Bale và Benzema chắc chắn sẽ ra sân trong khi đó tài năng trẻ Marcos Asensio sẽ đảm nhận vai trò hộ công.\r\n\r\n\r\nChia lửa tuyến giữa cùng cầu thủ người Tây Ban Nha còn bộ đôi người Croatia Modric và Kovacic trong khi Casemiro sẽ đảm nhận vị trí quét bóng ngay phía trước bộ đôi trung vệ.'),
(8, 'http://image.24h.com.vn/upload/1-2018/images/2018-03-31/Ronaldo-Messi-rm2-1522451400-138-width660height371.jpg', 'Ronaldo, Messi & 3 tháng \"sinh tử chiến\": Quả bóng Vàng thứ 6 về tay ai?', 'Tính đến thời điểm này, cả Messi và Ronaldo đều đã có 4 lần sở hữu giải Chiếc giày vàng châu Âu, 1 lần giành giải cầu thủ xuất sắc nhất thế giới, 4 lần vô địch Champions League, giành 3 siêu cúp châu Âu và 3 cúp thế giới các CLB.Nhưng quan trọng hơn cả là với 10 Quả bóng Vàng, Messi (5) và Ronaldo (5) đã và đang tạo ra giai đoạn thống trị trong cuộc đua danh hiệu cá nhân danh giá nhất thế giới. \r\n\r\nTờ Marca nhận định, Cristiano Ronaldo và Lionel Messi sẽ có giai đoạn nước rút quan trọng ở mùa bóng năm nay để phân định người thắng, kẻ bại trong cuộc đua đến danh hiệu Quả bóng Vàng 2018. Bởi lẽ, bất cứ ngôi sao nào giành chiến thắng mùa này, sẽ có thể tạo ra bước ngoặt và dấu ấn lớn trước đối thủ.\r\n\r\nTại La Liga, Lionel Messi đang nhỉnh hơn Cristiano Ronaldo về thành tích ghi bàn (25 so với 22). Chính điều này đang giúp cho Leo vẫn chiếm lợi thế trong cuộc đua giành danh hiệu Pichichi (vua phá lưới La Liga) và giành nhiều điểm số hơn trong cuộc đua Chiếc giày vàng châu Âu.\r\n\r\nNhưng ở Champions League, Ronaldo vẫn đang là người dẫn đầu với tổng cộng 12 bàn thắng được ghi. Thậm chí, nhiều người đang hy vọng CR7 sẽ giành kỳ tích lịch sử với 3 lần vô địch C1 liên tiếp với Real Madrid trong mùa giải 2017/18.\r\n\r\nNếu như Ronaldo giành cúp C1, còn Messi đoạt La Liga và cúp nhà Vua, nhiều khả năng cuộc đua giành Quả bóng Vàng năm nay sẽ phải phân định thắng thua trong cuộc chiến tại World Cup 2018.\r\n\r\nTrong sự nghiệp cầu thủ, cả hai ngôi sao vẫn chưa được hưởng vị ngọt chiến thắng tại ngày hội bóng đá lớn nhất hành tinh. Đội tuyển Argentina của Messi vào chung kết World Cup 2014, nhưng thất bại 0-1 trước đội tuyển Đức sau 120 phút.\r\n\r\nỞ chiều ngược lại, Cristiano Ronaldo đã cùng Bồ Đào Nha xuất sắc vô địch EURO 2016. Mục tiêu số một của anh là giúp đội tuyển quốc gia giành cúp vàng thế giới.'),
(9, 'http://image.24h.com.vn/upload/1-2018/images/2018-03-31/Ibra-gia-tu-MU-den-My-lam-VUA-Tai-tao-giac-mo-David-Beckham-20-ibra1-1522435466-428-width660height347.jpg', 'Ibrahimovic giã từ MU, đến Mỹ làm “VUA”: Giấc mơ David Beckham 2.0', 'Sau gần 2 năm thi đấu cho MU, cuộc phiêu lưu của Ibrahimovic ở xứ sương mù cuối cùng cũng đến hồi kết. Chắc chắn, các CĐV của đội chủ sân Old Trafford sẽ không quên tiền đạo lão tướng này.28 bàn/46 trận trên mọi đấu trường, trong đó có 17 bàn/28 trận ở Premier League, cùng với rất nhiều pha lập công quan trọng đưa “Quỷ đỏ” tới 3 danh hiệu. Dưới thời Jose Mourinho, chưa ai có tầm ảnh hưởng bao trùm cả MU như Ibrahimovic của mùa giải trước.  \r\n\r\nTuy nhiên, Ibra đã chọn cách ra đi ngay sau khi MU không thể giúp anh hoàn thành giấc mơ Champions League. Tiền đạo người Thụy Điển đã đồng ý hợp đồng 2,5 năm với LA Galaxy.\r\n\r\n“Những năm thi đấu ở châu Âu, tôi đã khoác áo nhiều câu lạc bộ danh tiếng và thi đấu cùng các cầu thủ hàng đầu thế giới. Tôi giành được 33 danh hiệu và muốn đến Mỹ để giành chiến thắng. Tôi chọn LA Galaxy để thực hiện mục tiêu”. Chân sút người Thụy Điển chia sẻ.\r\n\r\nBỏ lại sau lưng tất cả, Ibra đã được chào đón hết sức nồng nhiệt sau khi đặt chân đến nước Mỹ. Và thật bất ngờ khi chân sút người Thụy Điển chính là cầu thủ nổi tiếng nhất đầu quân cho MLS kể từ ngày David Beckham tới đây thi đấu 1 thập niên trước.'),
(10, 'http://image.24h.com.vn/upload/1-2018/images/2018-03-31/Xuan-Truong-Cong-Phuong-tai-xuat-V-League-Bi-hiem-huu_1259-1522494422-459-width660height415.jpg', 'Xuân Trường, Công Phượng tái xuất V-League: Bí hiểm & tập bài lạ', 'Chiều 31/3, HAGL có buổi tập trên sân Pleiku để chuẩn bị cho trận gặp Nam Định ở vòng 4 Nuti Cafe V-League 2018. Giám đốc kỹ thuật Chung Hae Soung quyết định buổi tập của HAGL tiếp tục là buổi tập kín và truyền thông chỉ được tác nghiệp trong 10 phút đầu tiên.Giải thích về sự \"bí hiểm\" của HAGL khi đóng cửa tập kín trước mỗi trận đấu, HLV Dương Minh Ninh cho hay: \"Trước tiên, chúng tôi muốn chiến thuật của HAGL được giữ kín hoàn toàn trước mỗi trận đấu. Mặt khác, các cầu thủ cũng tập trung tối đa khi tập luyện không có sự quan sát của truyền thông.\" Trước khi buổi tập của HAGL bắt đầu, ông Chung Hae Soung và các đồng sự cho Xuân Trường cùng đồng đội tập \"bài tập lạ\" nhằm giải phóng sức ì, nhất là đối với các tuyển thủ Việt Nam vừa thi đấu ở Jordan trở về. Theo đó, các cầu thủ HAGL sẽ ngồi tựa lưng nhau, hoặc nằm sấp đối diện nhau ở vạch vôi giữa sân để chờ lệnh của trợ lý Nguyễn Văn Đàn. Khi HLV Nguyễn Văn Đàn phát lệnh và chạy về hướng nào thì Công Phượng cùng đồng đội phải chạy về hướng ngược lại...Xuân Trường cùng đồng đội tỏ ra rất vui với bài tập kể trên của ban huấn luyện HAGL.');

-- --------------------------------------------------------

--
-- Table structure for table `baivietanh`
--

CREATE TABLE `baivietanh` (
  `id` int(10) UNSIGNED NOT NULL,
  `anh` varchar(200) COLLATE utf8_unicode_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
-- Dumping data for table `baivietanh`
--

INSERT INTO `baivietanh` (`id`, `anh`) VALUES
(1, 'http://image.24h.com.vn/upload/1-2018/images/2018-03-31/Video-ket-qua-bong-da-MU---Swansea-Phu-dau-kho-tin-mu-5-1522508139-243-width660height422.jpg'),
(2, 'http://image.24h.com.vn/upload/2-2018/images/2018-04-01/Video-ket-qua-bong-da-Everton---Man-City-m-c2-1522517457-212-width660height396.jpg'),
(3, 'http://image.24h.com.vn/upload/1-2018/images/2018-03-31/Tin-the-thao-HOT-1-4-Djokovic-chia-tay-HLV-Agassi-d1-1522513610-785-width660height371.jpg'),
(4, 'http://image.24h.com.vn/upload/2-2018/images/2018-04-01/Video-ket-qua-bong-da-PSG---Monaco-dzpami_xkaeuh6y-1522531318-763-width660height368.jpg'),
(5, 'http://image.24h.com.vn/upload/1-2018/images/2018-03-05/Bang-xep-hang-tennis-5-3-Nadal-bi-dau-van-de-doa-so-1-Federer-qua-dau-dau-federer_nadal-1520236864-469-width660height415.jpg'),
(6, 'http://image.24h.com.vn/upload/1-2018/images/2018-03-12/Hang-khung-Trung-Quoc-20-tuoi-2m11-ghi-diem-nhu-may-nguoi-My-phat-cuong-bongro5-1520852683-449-width660height468.jpg'),
(7, 'http://image.24h.com.vn/upload/1-2018/images/2018-03-31/Tien-thuong-cho-U23-Viet-Nam-can-moc-cuc-khung-014659-u23vn-1522489866-422-width660height371.jpg'),
(8, 'http://image.24h.com.vn/upload/1-2018/images/2018-03-29/Thay-Park-va-niem-tin-cao-hon-top-100-the-gioi-vn1-1522284410-39-width660height495.jpg'),
(9, 'http://image.24h.com.vn/upload/1-2018/images/2018-03-24/Real-dai-loan-Ba-sieu-anh-hung-hop-luc-lat-ghe-Zidane-real2-1521897532-732-width660height449.jpg'),
(10, 'http://image.24h.com.vn/upload/1-2018/images/2018-03-15/MU-mu3-1521114143-822-width660height440.jpg');

-- --------------------------------------------------------

--
-- Table structure for table `baivietbongro`
--

CREATE TABLE `baivietbongro` (
  `id` int(10) UNSIGNED NOT NULL,
  `anh` varchar(200) COLLATE utf8_unicode_ci NOT NULL,
  `tieude` varchar(200) COLLATE utf8_unicode_ci NOT NULL,
  `noidung` text COLLATE utf8_unicode_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
-- Dumping data for table `baivietbongro`
--

INSERT INTO `baivietbongro` (`id`, `anh`, `tieude`, `noidung`) VALUES
(1, 'http://image.24h.com.vn/upload/1-2018/images/2018-03-14/VUA-bong-ro-thi-trien-tuyet-ki-sadfasdff-1521040946-157-width660height500.jpg', 'Đọ chiêu \"lườm rau gắp thịt\", Ronaldinho phải nể \"Vua bóng rổ\"', 'Bóng đá từng sản sinh ra Ronaldinho - \"nhà ảo thuật\" trên sân cỏ với nhiều tuyệt kĩ làm xiếc với trái bóng vô cùng điệu nghệ, một trong số đó phải kể đến \"lườm rau gắp thịt\". Đây là tuyệt kĩ đánh lạc hướng đối phương bằng đôi mắt những chuyền bóng theo hướng khác. Trong lịch sử, NHM từng được chứng kiến nhiều danh thủ nổi tiếng sử dụng \"lườm rau gắp thịt\" như Francesco Totti, Cristiano Ronaldo, Thierry Henry, nhưng không ai để lại ấn tượng mạnh mẽ như Ronaldinho.\r\n\r\nNếu bóng đá có \"vua kĩ thuật\" Ronaldinho thì bóng rổ cũng tự hào với LeBron James. Mới đây ngôi sao được mệnh danh \"Vua bóng rổ\" đã tái hiện hoàn hảo tuyệt kĩ \"lườm rau gắp thịt\" cho đồng đội Kyle Korver ghi điểm trong trận đấu giữa Los Angeles Lakers và Cleveland Cavaliers thuộc khuôn khổ giải bóng rổ nhà nghề Mỹ NBA. \r\n\r\nDù CLB Cleveland Cavaliers thúc thủ với tỉ số 127-113 chung cuộc, khoảnh khắc đỉnh cao của LeBron James vẫn sẽ được fan nhắc đến suốt thời gian dài. Cũng phải nói thêm rằng đây không phải lần đầu tiên LeBron James thi triển tuyệt chiêu này.'),
(2, 'http://image.24h.com.vn/upload/1-2018/images/2018-03-03/Houston-Rockets---Bolton-Celtics-Long-tranh-ho-dau-bong-ro1-1520073628-989-width660height464.jpg', 'Bóng rổ Mỹ NBA: Long tranh hổ đấu, ngôi sao so tài\r\nThứ Bảy, ngày 03/03/2018 17:42 PM (GMT+7)', 'Một mùa giải với rất nhiều bất ngờ thú vị khi Houston Rockets và Bolton Celtics đang khẳng định mình là những ứng cử viên vô địch của năm. Họ được đánh giá cao hơn cả hai CLB vào đến NBA Final năm ngoái là Golden State Warriors và Cleveland Cavaliers. Đặc biệt với Houston Rockets, Jame Harden đã cho thấy anh là nhân tố quan trọng nhất. Mùa giải năm nay, Jame Harden đã thực sự toả sáng, anh đang dẫn đầu danh sách Cầu thủ xuất sắc nhất mùa. Anh dẫn đầu danh sách các cầu thủ ghi điểm nhiều nhất giải, đứng thứ ba danh sách chuyền bóng và đặc biệt đứng đầu danh sách ghi được 3 điểm. Thành tích xuất sắc này đã giúp CLB Houston Rockets đứng đầu khu vực miền Tây. Ngôi sao Jame Harden chia sẻ: \"Đây là năm của chúng tôi, khi lãnh đạo CLB đã đem về những con người tốt như Eric Gordon và Ryan Andeson... Thật sự một đội hình tốt nhất mà tôi từng được thi đấu cùng”.\r\n\r\nCùng với đó, Bolton Celtics tiếp tục cho thấy họ tiếp tục khẳng định vị thế của mình khi thi đấu ấn tượng với Jayson Tatum, một ngôi sao trẻ của làng bóng rổ Mỹ. Dù chỉ mới 20 tuổi, nhưng cầu thủ từng gây sốt khi còn thi đấu ở trường Đại học đã ghi trung bình mỗi trận 13,3 điểm.'),
(3, 'http://image.24h.com.vn/upload/1-2018/images/2018-03-07/ong-trum-lam-tien-nhat-the-thao-2018-Abramovich-hit-khoi-baobinh1-1520419676-82-width660height331.jpg', 'Ông trùm tỷ đô siêu giàu: Abramovich hít khói \"đại ca\" bóng rổ 2018', 'Roman Abramovich từng là người giàu nhất nước Nga và đứng 11 thế giới với số tài khoản lên tới 18,2 tỷ USD vào 2006 do tạp chí Forbes xếp hạng. Ông chủ của CLB bóng đá Chelsea, từng nhiều lần xếp hạng vào top 10 \"đại ca\" giàu nhất làng thể thao, năm nay cũng vậy nhưng số tài khoản của Abramovich hiện tại kém hơn rất nhiều so với các đại gia thể thao khác. Cũng theo Forbes, số tiền của Abramovich trong năm 2018 vào khoảng 10,8 tỷ USD đứng thứ 140 thế giới. Nếu so sánh với tỷ phú người Mỹ - Steve Ballmer (38,4 tỷ USD) người đang là giám đốc điều hành Microsoft và là ông chủ CLB bóng rổ Los Angeles Clippers tại giải NBA thì chủ tịch Chelsea thua kém rất nhiều.\r\n\r\nSố tiền của Abramovich thâm hụt so với nhiều năm trước, khiến vị thế của ông cũng không được đánh giá cao trên bảng xếp hạng, nó cũng giống như tình cảnh của CLB Chelsea trong mùa 2017/18. Quả thật, đây là một tin chẳng vui một chút nào với fan của \"The Blue\".\r\n\r\nTheo xếp hạng trên Forbes, hiện tại những tỷ phú đầu tư vào thể thao cũng chẳng phải những người quá giàu có. Họ sở hữu số tài khoản trung bình so với các tỷ phú khác và chỉ kinh doanh tay ngang chứ không chuyên nghiệp.'),
(4, 'http://anh.24h.com.vn/upload/4-2017/images/2017-11-08/Cu-soc-the-thao-My-di-tu-160-nam-vi-di-dem-2-ty-VNd-bongro1-1510128804-119-width660height430.jpg', 'Cú sốc thể thao Mỹ: 2 \"bố già\" rũ tù 160 năm vì “đi đêm” 2 tỷ VNĐ', 'Mới đây, một bồi thẩm đoàn liên bang ở New York đã buộc tội 2 cựu thành viên bóng rổ nhà nghề Mỹ NBA gồm Chuck Person (cầu thủ) Rashan Michel (trọng tài), đây là 2 trong số 10 người đang bị giam giữ vì liên quan tới nạn tham nhũng bóng rổ đại học gây rúng động thể thao Mỹ thời gian qua. FBI và Bộ Tư pháp Mỹ đã công bố những bằng chứng xác thực và họ mô tả là \"bóng tối\" của bóng rổ đại học vào hôm 26/9. Theo bản cáo trạng, cựu cầu thủ NBA đối mặt với tối danh nhận hối lộ 91.500 USD (hơn 2 tỷ VNĐ) và hối lộ 18.500 USD (hơn 400 triệu VNĐ) khi ông còn làm HLV của trường đại học Auburn (Mỹ), theo Dailymail ông sẽ phải đối mặt với án tù giam lên tới 80 năm.\r\n\r\nNgười thứ 2 liên quan tới vụ việc này là cựu trọng tài NBA, ông Rashan Michel đối mặt với các tội danh hối lộ và nhận hối lộ, người đàn ông 43 tuổi cũng liên quan tới việc dàn xếp tỷ số trong thời gian cầm còi. Ông này cũng sẽ đối mặt tới án tù giam lên tới 80 năm.\r\n\r\nNhư vậy tổng án tù mà hai cựu thành viên của giải NBA Chuck Person và Rashan Michel lên tới 160 năm, điều này sẽ trở thành hiện thực nếu hai cựu \"ngôi sao\" này không chứng minh được mình vô tội trong những phiên điều trần tiếp theo.'),
(5, 'http://anh.24h.com.vn/upload/3-2017/images/2017-08-11/1502397525-hop-bao-vba-2017_17.jpg', 'SEA Games: ĐT bóng rổ Việt Nam treo thưởng cực độc', 'Chiều ngày 10/8, tại TP HCM đã diễn ra buổi họp báo công bố mùa giải bóng rổ chuyên nghiệp Việt Nam 2017 (VBA 2017). Tiếp nối thành công nhất định của giải bóng rổ chuyên nghiệp Việt Nam 2016 (VBA), giải đấu được bầu chọn là 1 trong 5 sự kiện trong năm 2016 có sức ảnh hưởng tích cực đến giới trẻ, VBA 2017 với mùa giải mới hứa hẹn bùng nổ hơn cùng nhiều hoạt động mới và hấp dẫn, bắt đầu từ ngày 5/9/2017. VBA 2017 với sự xuất hiện của một thành viên mới, một đại diện nữa đến từ thủ đô Hà Nội - Thăng Long Warriors (TLW) – nâng tổng số đội tham gia tranh tài tại giải là 6 đội. Đặc biệt, lần đầu tiên tại VBA cũng như trong lịch sử thể thao chuyên nghiệp tại Việt Nam, chủ sở hữu đội bóng là một nữ doanh nhân – Bà Tracy Thư Lương – một người có nhiều tình cảm và đam mê với bộ môn bóng rổ.\r\n\r\n“Bóng rổ không chỉ là một môn thể thao đơn thuần, đây còn có thể được xem là một phương tiện giải trí hiện đại đầy hấp dẫn. Bóng rổ đang phát triển rất mạnh và VBA sẽ góp một phần không nhỏ để đẩy mạnh bộ môn thể thao này tại Việt Nam. Chúng ta luôn cần có một giải đấu chuyên nghiệp để có thể phát triển mạnh mẽ bất kỳ môn thể thao nào.'),
(6, 'https://i-thethao.vnecdn.net/2018/03/30/top-1136-1522400507.jpg', 'Kevin Durant bị đuổi trong ngày trở lại NBA', 'Trở lại NBA lần đầu tiên sau hai tuần ngồi ngoài vì chấn thương sườn, Kevin Durant có vẻ như chưa quen với những va chạm. Anh tỏ ra ức chế quá mức cần thiết sau tình huống bị phạm lỗi khi lên rổ ở cuối hiệp hai.\r\n\r\nNhưng trọng tài Tre Maddox không nghĩ đó là pha bóng phạm luật của hàng thủ Bucks. Cơn lôi đình của Durant nổi lên, siêu sao của Warriors dành những lời khó nghe cho vị vua áo đen. Kết quả, Durant nhận hai lỗi kỹ thuật liên tiếp, bị đuổi khỏi sân. “Sau khi thổi lỗi kỹ thuật thứ nhất cho Durant, trọng tài đã cố bỏ qua. Nhưng Durant tiếp tục nói những lời lẽ thô tục, khiến Maddox buộc phải thổi lỗi kỹ thuật thứ hai”, tổng trọng tài Bill Kennedy nói với báo chí.\r\n\r\nDurant lúc đầu không tin rằng anh bị đuổi. Anh ngồi trên băng ghế huấn luyện của Warriors, nhưng bị buộc rời khỏi sân ngay lập tức.\r\n\r\n“Rõ ràng tôi đã bị phạm lỗi”, Durant nói. “Tôi nói với ông ấy cảm xúc của mình, và thế là ông ấy đuổi tôi”.\r\n\r\nTrong 17 phút có mặt trên sân, Durant ghi 10 điểm. Đây là lần thứ năm MVP năm 2014 bị đuổi ở mùa này, nhiều thứ nhì trong lịch sử NBA (chỉ kém Rasheed Wallace, bị đuổi bảy lần mùa 2000 và 2001).'),
(7, 'https://i-thethao.vnecdn.net/2018/03/26/67ers-8204-1522055943.jpg', 'Philadelphia 76ers lần đầu vào play-off NBA sau sáu năm', 'Indiana Pacers, sau khi thắng Heat, cũng giành luôn vé play-off. Như vậy, miền Đông đã có năm đội lọt vào vòng đấu loại trực tiếp, gồm Toronto Raptors, Boston Celtics, Cleveland Cavaliers, Philadelphia 76ers và Indiana Pacers.\r\n\r\nTrong số này, chiến tích của 76ers là đáng nói nhất, bởi đội bóng đến từ Philadelphia chỉ xếp thứ 14 trong số 15 đội miền Đông mùa trước.\r\n\r\nMùa này, 76ers giành vé sớm 10 lượt đấu, nhờ sự gia cố đáng kể về lực lượng. Họ là đội xếp chót hoặc áp chót bảng thứ bậc NBA trong nhiều mùa liên tiếp. Nhờ đó, 76ers luôn được sở hữu những lựa chọn đầu tại các kì Draft, đồng nghĩa với những tân binh chất lượng.\r\n\r\nVận rủi đeo bám đội bóng này trong nhiều mùa giải, khi những ngôi sao trẻ được lựa chọn đều dính chấn thương nặng và phải nghỉ toàn bộ mùa giải đầu tiên. Năm nay cũng vậy, 76ers chọn Markelle Fultz ở lượt đầu tiên, nhưng anh này dành cả mùa giải để dưỡng thương. Dẫu vậy, kết quả của 76ers đã không còn tệ, khi họ có sự trở lại của những pick đầu ở các mùa trước, đó là trung phong người Cameroon Joel Embiid (pick số ba năm 2014) và Ben Simmons (pick số một năm 2016).'),
(8, 'https://i-thethao.vnecdn.net/2018/03/28/Ball-8309-1522232012.jpg', 'Cầu thủ trẻ bóng rổ Mỹ bị lật tẩy vụ dàn xếp ghi 72 điểm', 'Ông bố LaVar của ba anh em nhà Ball xưa nay vẫn là nhân vật bị ghét nhất trong làng bóng rổ Mỹ. Nhân vật này từng có nhiều phát ngôn ngạo mạn và lố bịch liên quan đến cậu con trai cả Lonzo Ball, khiến hậu vệ của LA Lakers bị ghét lây dù không làm gì sai trái.\r\n\r\nMới đây, câu chuyện “bố hại con” tái diễn, lần này nạn nhân là cậu con trai thứ hai LiAngelo Ball. Chỉ vài giờ sau khi LiAngelo tuyên bố góp mặt tại kì Draft của NBA mùa hè này, cha anh tạo ra một màn kịch để “nâng giá” cho cầu thủ đang thi đấu tại Lithuania. Làng bóng rổ Mỹ, báo chí và các trang mạng xã hội “dậy sóng” khi LiAngelo Ball ghi tới 72 điểm trong trận đấu mới đây cho đội Vytautas của Lithuania. Chàng trai 19 tuổi nhận được hàng loạt mỹ từ ca ngợi. Nhưng sau đó, truyền thông Mỹ phát hiện ra trận đấu chỉ là sự sắp đặt của nhà Ball.\r\n\r\nGia đình Ball sở hữu thương hiệu thời trang Big Baller Brand (BBB), nhà tài trợ của giải Big Baller Brand International. Tại giải đấu giao hữu kéo dài ba trận, đội Vytautas so tài với Guangdong Southern Tigers của giải bóng rổ chuyên nghiệp Trung Quốc. Đây chính là trận đấu mà LiAngelo Ball ghi 72 điểm (Vytautas thắng 159-116).'),
(9, 'https://i-thethao.vnecdn.net/2017/12/11/Ball-4456-1512984831.jpg', 'NBA phẫn nộ vì phát biểu ngông cuồng của bố sao trẻ Lakers', 'Người hâm mộ NBA tại Mỹ lại được dịp phẫn nộ với LaVar Ball, người cha nổi tiếng ngạo mạn của tài năng trẻ Lonzo Ball. Kể từ khi cậu cả nhà Ball gia nhập LA Lakers, ông LaVar luôn tâng con trai lên mây xanh, đồng thời dành những lời xấu xí để nói về Lakers. Sự phẫn nộ của cộng đồng lên đến đỉnh điểm, khi LaVar khẳng định ông mới là người xứng đáng dẫn dắt đội bóng này.\r\n\r\n\"Tôi năm nay 50 tuổi, biết tất tần tật về NBA. Hãy xem HLV của Lakers hiện nay, Luke Walton mới 38 tuổi, quá thiếu kinh nghiệm để dẫn dắt đội bóng. Mọi người nói rằng Lakers hiện tại chơi không tốt vì các cầu thủ quá trẻ. Không. Hãy thử để tôi dẫn dắt đội này xem, đảm bảo Lakers sẽ hay hơn bây giờ nhiều\", LaVar Ball nói chắc như đinh đóng cột.\r\n\r\nCách đây hai tuần, LaVar Ball tuyên bố thẳng thừng rằng ban huấn luyện của Lakers hiện không đủ trình độ để có thể huấn luyện con trai Lonzo Ball của ông. Đáp lại, HLV Luke Walton chỉ nói nhẹ nhàng nhưng không kém phần thâm thúy: \"Chúng tôi ngồi đây không phải để tiếp nhận những ý kiến đóng góp từ những người chả có chuyên môn gì\". LaVar Ball luôn hung hăng và ngông cuồng khi trả lời giới truyền thông. Ông lộng ngôn đến mức, ban lãnh đạo của Lakers phải đặt ra một quy định mới, có tên “LaVar Ball rule”. Đó là cấm tất cả phóng viên không được tiếp cận thành viên trong gia đình của các cầu thủ sau khi trận đấu kết thúc.'),
(10, 'https://i-thethao.vnecdn.net/2018/03/25/top-3133-1521954529.jpg', 'Saigon Heat dự play-off giải bóng rổ Đông Nam Á với vị trí thứ sáu', 'Saigon Heat phải thắng cách biệt 19 điểm mới có thể lấy được vị trí thứ năm từ tay Slingers, đội hơn họ một trận thắng và hơn cả thành tích đối đầu.\r\n\r\nĐội chủ sân CIS có khởi đầu không tồi, dẫn 28-25 ở hiệp đầu tiên. Nhưng ba hiệp sau đó lại là hình ảnh bạc nhược của đại diện Việt Nam. Là đội lập kỷ lục về số cú ném ba điểm trong một mùa giải ABL, nhưng Heat chỉ ném thành công sáu quả ba điểm ở trận này. Hhàng thủ Slingers chơi quá tốt, không cho các tay ném chủ nhà có đủ không gian và thời gian để dứt điểm chuẩn xác.\r\n\r\nMặt khác, những pha lên rổ sở trường của ngôi sao Akeem Scott cũng không được phát huy, khi cầu thủ của Heat phải đối đầu với một Xavier Alexander quá mạnh mẽ bên phía Slingers.\r\n\r\nKhông chỉ mạnh trong phòng ngự, Slingers còn sắc sảo trong tấn công. Trong ngày trung phong Chris Charles mắc nhiều lỗi từ sớm, nhiệm vụ “tả xung hữu đột” được nhường lại cho ngoại binh còn lại Xavier Alexander. Tiền phong của Slingers ghi tới 38 điểm, có 14 rebound và bảy kiến tạo. Sự xuất sắc của anh giúp đại diện Singapore dẫn bảy điểm sau hai hiệp đầu, dẫn 15 điểm sau ba hiệp và thắng chung cuộc 97-77.');

-- --------------------------------------------------------

--
-- Table structure for table `baiviethot`
--

CREATE TABLE `baiviethot` (
  `id` int(10) UNSIGNED NOT NULL,
  `anh` varchar(200) COLLATE utf8_unicode_ci NOT NULL,
  `tieude` varchar(200) COLLATE utf8_unicode_ci NOT NULL,
  `noidung` text COLLATE utf8_unicode_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
-- Dumping data for table `baiviethot`
--

INSERT INTO `baiviethot` (`id`, `anh`, `tieude`, `noidung`) VALUES
(1, 'http://image.24h.com.vn/upload/2-2018/images/2018-04-01/Chuyen-nhuong-MU-Chi-hon-100-trieu-bang-mua-hau-ve-Barca-va-Juventus-collage_photocat-1522580421-251-width660height334.jpg', 'Chuyển nhượng MU: Chi hơn 100 triệu bảng mua hậu vệ Barca và Juventus', 'MU bạo chi 100 triệu bảng, Mourinho mơ giải cứu “kẻ nổi loạn” Barca, đua Chelsea săn sao Juventus\r\n\r\nTheo nguồn tin thân cận từ cây viết uy tín Duncan Castle của tờ Sunday Times, MU đang gấp rút tiến hành việc tiếp cận 2 mục tiêu chuyển nhượng hàng đầu mà HLV Mourinho nhắm đến để gia cố hàng thủ “Quỷ đỏ” hè này.\r\n\r\nĐó là trung vệ Samuel Umtiti (Barcelona) và hậu vệ trái Alex Sandro (Juventus). Với Umtiti, cầu thủ người Pháp này có mức phí giải phóng hợp đồng là 52,5 triệu bảng và đã thất bại trong yêu sách đòi tăng lương lên tới 8 triệu bảng/năm, gấp đôi mức lương hiện tại đang nhận ở Barca nên khả năng anh ra đi hè này là không nhỏ. Còn với Alex Sandro, Juve sẵn sàng bán tuyển thủ Brazil với giá 50 triệu bảng nhưng MU sẽ phải nỗ lực cạnh tranh với Chelsea để mơ có anh. Lờ Juventus, MU ưu tiên đẩy Martial sang Real để giảm tiền mua Bale\r\n\r\nMặc dù Juve được cho là rất muốn có sự phục vụ của Anthony Martial nhưng MU có vẻ không muốn để tiền đạo người Pháp sang Ý thi đấu. Thay vào đó, theo tờ Mirror, “Quỷ đỏ” muốn đưa “Tiểu Henry” sang Real Madrid như một phần hợp đồng để Gareth Bale di chuyển theo chiều ngược lại đến với sân Old Trafford.\r\n\r\nNgôi sao người xứ Wales vẫn được định giá hiện tại lên tới 90 triệu bảng và MU muốn trao đổi Martial để giảm bớt khoản phí chuyển nhượng ngất ngưởng này.\r\n\r\nGriezmann chọn Barca thay vì MU\r\n\r\nBất chấp việc MU đã theo đuổi Antoine Griezmann từ rất lâu nhưng ngôi sao chạy cánh người Pháp của Atletico Madrid vẫn khá dửng dưng với “Quỷ đỏ”. Theo tờ The Sun, bất chấp việc Paul Pogba là bạn đồng hương thân thiết với mình ở ĐT Pháp, Griezmann vẫn nhất quyết sẽ chuyển sang Barcelona thay vì MU hè này với giá chuyển nhượng 88 triệu bảng, dù biết, ở Nou Camp, anh sẽ phải cạnh tranh vị trí đá chính trên hàng công rất căng thẳng.'),
(2, 'http://image.24h.com.vn/upload/2-2018/images/2018-04-01/Tin-HOT-bong-da-trua-1-4-Chelsea-nham-Terry-moi-jamaal-lascelles-1522559600-654-width660height440.jpg', 'Tin HOT bóng đá tối 1/4: Barca nhắm SAO Atletico', 'Barca nhắm SAO Atletico: Tới thời điểm này, Barca vẫn chưa thể thuyết phục được Samuel Umtiti gia hạn hợp đồng. Theo Don Balon, đội chủ sân Nou Camp vì thế đã nhắm tới Lucas Hernandez của Atletico Madrid (giá khoảng 40-50 triệu euro) như một giải pháp thay thế. Dù mới 22 tuổi nhưng anh đã có 3 năm chơi cho đội 1 của Atletico.\r\n\r\nLukaku nhận tin sét đánh: Trong ngày cán mốc đáng nhớ 100 bàn ở Premier League, Lukaku đã được gia đình báo tin buồn. Theo đó, người anh em con nhà bác ruột của anh là Nathan Ito Kavuanda, tay rapper 23 tuổi nổi tiếng, bị kết án 5 năm tù giam vì tội hiếp dâm.\r\n\r\nBayern không kí hợp đồng với HLV Dortmund: Giám đốc điều hành của Bayern Munich, Karl-Heinz Rummenigge xác nhận HLV Thomas Tuchel đã kí hợp đồng với một đội bóng khác và đó không phải \"Hùm xám\". Báo giới Đức tiết lộ cựu thuyền trưởng Dortmund nhận lời ra nước ngoài làm việc, Premier League, cụ thể là Arsenal được cho là điểm đến mong muốn của chiến lược gia 44 tuổi.\r\n\r\nSao Real lần đầu dính chấn thương trong sự nghiệp: Real thắng dễ Las Palmas 3-0 nhưng họ mất Nacho. Theo chẩn đoán, Nacho gặp vấn đề với gân kheo khi cảm thấy không thoải mái sau một nỗ lực dứt điểm. Đáng chú ý, đây mới là lần đầu tiên trong sự nghiệp chuyên nghiệp kể từ khi khoác áo đội 1 Real (155 trận), hậu vệ 28 tuổi người TBN dính chấn thương.\r\n\r\nLộ ứng viên thay Conte ở Chelsea: Tối nay, Chelsea sẽ tiếp đón Tottenham tới sân nhà tại vòng 32 Premier League. Trận đấu có tính chất đặc biệt quan trọng trong cuộc đua giành vị trí trong tốp 4 được dự Champions League. Theo những gì báo chí Anh đăng tải, nếu Chelsea để thua Spurs, khả năng HLV Antonio Conte bị sa thải là rất lớn. Và éo le thay, trong tương lai, chính đồng nghiệp Mauricio Pochettino sẽ thế chỗ ông.\r\n\r\n\r\nChelsea nhắm “Terry mới”: Trung vệ Jamaal Lascelles đang chơi rất hay trong màu áo Newcastle United  dưới sự dẫn dắt của HLV Rafa Benitez. Điều này gây ấn tượng mạnh với HLV Conte và ông muốn Chelsea chiêu mộ cầu thủ có biệt danh “Terry mới” để thay thế Gary Cahill và David Luiz, bộ đôi nhiều khả năng rời CLB hè này. Ước tính, thương vụ này rơi vào khoảng 30-40 triệu bảng. Ầm ĩ sau đại chiến Juventus-Milan: Trận thua đau đớn trước đội đầu bảng khiến HLV Gattsuso không giữ nổi bình tĩnh và thẳng thắn chỉ trích tiền vệ Calhanoglu, người bị ông cho là thi đấu không thực sự cố gắng. Trong khi đó, trung vệ Bonucci cảm thấy bị xúc phạm với những tiếng la ó trên khán đài SVĐ Allianz trong ngày anh trở lại: “Tôi định không ăn mừng bàn thắng ấy nhưng cái cách CĐV Juventus chào đón tôi khiến tôi cảm thấy mình không được tôn trọng nên tôi đã ăn mừng.”'),
(3, 'http://image.24h.com.vn/upload/1-2018/images/2018-03-31/Video-ket-qua-bong-da-Inter-Milan---Hellas-Verona-inter1-1522508240-557-width660height371.jpg', 'Inter Milan - Hellas Verona: Song tấu rực rỡ, choáng ngay phút thứ 1', 'Gặp đội trong nhóm cầm đèn đỏ Hellas Verona là cơ hội tốt để Inter Milan giành chiến thắng, nuôi hi vọng giành vé dự Champions League mùa sau. Ngay phút đầu tiên, đội chủ nhà đã mở tỷ số do công đội trưởng Icardi từ đường kiến tạo của Perisic. Trên đà hưng phấn, Inter nhân đôi cách biệt phút 13. Lần này chính mục tiêu của MU hồi hè 2017 - Perisic lập công. Thời gian sau đó, đội chủ sân Giuseppe Meazza kiểm soát cuộc chơi, tạo thêm nhiều tình huống hãm thành Hellas Verona.\r\n\r\nĐầu hiệp 2, Icardi hoàn tất cú đúp. Dẫn 3-0, Inter chơi thong dong trong khi đội khách mất hết tinh thần. Đó cũng là tỷ số cuối cùng. \"Nerazzurri\" sẽ đá bù gặp Milan vào ngày 4/4 tới và nếu thắng, họ sẽ vào tốp 3.\r\n\r\nTỷ số trận đấu:  Inter Milan 3-0 Hellas Verona\r\n\r\nGhi bàn: Icardi (1\' - 48\'), Perisic 13\'\r\n\r\nĐội hình xuất phát:\r\n\r\nInter Milan: 1 Samir Handanovic 7 Joao Cancelo 25 Miranda 33 Danilo D\'Ambrosio 37 Milan Skriniar 5 Roberto Gagliardini 77 Marcelo Brozovic 87 Antonio Candreva 8 Rafinha 44 Ivan Perisic 9 Mauro Icardi\r\n\r\nHellas Verona: 1 Nicolas 28 Alex Ferrari 12 Andrea Caracciolo 26 Jagos Vukovic 69 Samuel Souprayen 2 Romulo 23 Simone Calvano 16 Rolando Aarons 77 Marcel Buchel 93 Mohamed Fares 70 Bruno Petkovic');

-- --------------------------------------------------------

--
-- Table structure for table `baiviettennis`
--

CREATE TABLE `baiviettennis` (
  `id` int(10) UNSIGNED NOT NULL,
  `anh` varchar(200) COLLATE utf8_unicode_ci NOT NULL,
  `tieude` varchar(200) COLLATE utf8_unicode_ci NOT NULL,
  `noidung` text COLLATE utf8_unicode_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
-- Dumping data for table `baiviettennis`
--

INSERT INTO `baiviettennis` (`id`, `anh`, `tieude`, `noidung`) VALUES
(1, 'http://image.24h.com.vn/upload/1-2018/images/2018-03-30/Tin-the-thao-HOT-30-3-Federer-Nadal-bi-chi-trich-vi-khong-du-Davis-Cup-sadf-1522412642-132-width660height495.jpg', 'Tin thể thao HOT: Federer, Nadal bị chỉ trích vì không dự Davis Cup', 'Federer, Nadal bị chỉ trích vì vắng mặt ở Davis Cup: Kể từ khi cùng ĐT Thụy Sĩ lần đầu vô địch Davis Cup năm 2014, Roger Federer mới xuất hiện ở đấu trường này thêm 1 lần vào năm 2015. Trong khi đó, Rafael Nadal cũng vắng mặt suốt từ năm 2016 dù từng giúp ĐT Tây Ban Nha 4 lần lên ngôi ở đấu trường danh giá nhất làng quần vợt cấp đội tuyển (2004, 2008, 2009, 2011).Trước tình cảnh đó, Yannick Noah - cựu vô địch Roland Garros và là đội trưởng ĐT quần vợt Pháp đã bất ngờ \"đá xoáy\" hai tay vợt hàng đầu thế giới: \"Federer và Nadal thích chơi ở các giải đấu khác hơn Davis Cup là câu chuyện chẳng mấy hay ho gì\".\r\n\r\nMùa giải 2018, Thụy Sĩ đã bị loại ở vòng 1 trước Kazakhstan, còn TBN sẽ đụng độ Đức ở tứ kết.'),
(2, 'http://image.24h.com.vn/upload/1-2018/images/2018-03-30/Truc-tiep-tennis-Miami-Open-ngay-10-Cho-chung-ket-trong-mo-Del-Potro--Zverev-mi1-1522394069-535-width660height421.jpg', 'Miami Open ngày 10: Chờ chung kết trong mơ Del Potro – Zverev', 'Del Potro (5) – John Isner (14), 1h, 31/3, bán kết đơn nam\r\n\r\nDel Potro đang duy trì phong độ vô cùng ấn tượng. Anh đang băng băng trên con đường chinh phục danh hiệu thứ 3 liên tiếp trong năm 2018. Sau khi vô địch Acapulco, “Delpo” xuất sắc hạ gục Federer để đăng quang Indian Wells đầy thuyết phục.Tại Miami Open 2018, Del Potro đang tiếp tục thể hiện sức mạnh phi thường. Hạt giống số 4 sau khi vượt qua Haase, Nishikori và Krajinovic đã có màn kịch chiến đẳng cấp với Milos Raonic ở tứ kết.\r\n\r\nDù bị thua trước trong set 1 với tỷ số 5-7 nhưng Del Potro đã chứng tỏ bản lĩnh và đẳng cấp ở phần còn lại của trận đấu. “Tòa tháp Tandil” kéo đối thủ vào 2 loạt tie-break để rồi “bắn hạ” rất dễ dàng cùng tỷ số chênh lệch 7-1, 7-3.\r\n\r\nSau chiến thắng ngoạn mục đó, tinh thần của Del Potro đang lên ngút trời. Dù phải chạm trán tay vợt chủ nhà ở bán kết song “Delpo” được giới chuyên môn đánh giá rất cao. John Isner bị nghi ngờ về tính ổn định khi bất ngờ chơi hay tại Miami Open. Trước đó, hạt giống số 14 thua liên tiếp trận đầu tiên ở 3 giải đấu là Delray Beach, Acapulco và Indian Wells.\r\n\r\nThành tích đối đầu cũng đang ủng hộ Del Potro. 9 lần chạm trán trực tiếp từ năm 2008 đến nay, Isner nhận về 6 thất bại. Có 1 lần hai tay vợt đụng độ ở chung kết (Washington, 2013) và phần thắng cũng thuộc về Del Potro.\r\n\r\nAlexander Zverev (4) – Pablo Busta (16), 6h, 31/3, bán kết đơn nam\r\n\r\nAlexander Zverev đã có màn báo thù thành công trước Borna Coric tại bán kết. “Hoàng tử” nước Đức lập lại tỷ số 6-4, 6-4 giống như anh đã từng loại Nick Kyrgios trước đó. Điều này cho thấy Zverev đang rất tự tin và bản lĩnh để dứt điểm đối thủ ở thời khắc quyết định của trận đấu.'),
(3, 'http://image.24h.com.vn/upload/2-2018/images/2018-04-01/miami_open_tennis_77109-660-1522524681-176-width660height495.jpg', 'Ostapenko - Stephens: Phòng ngự đỉnh cao, đăng quang xứng đáng', 'Sloane Stephens, nhà vô địch đơn nữ US Open 2017, đã đánh bại Jelena Ostapenko với các tỷ số 7-6 (7-5) 6-1 trong trận chung kết đơn nữ Miami Open 2018 để đăng quang tại thành phố quê hương của mình. Mặc dù đối đầu với một đối thủ trẻ tuổi, nhiều năng lượng và thi đấu nhiệt huyết, nhưng Stephens tỏ rõ sự kinh nghiệm và kiên nhẫn với lối chơi của mình. Dựa vào khả năng phòng ngự lẫn cố ý kéo dài các pha đánh bóng bền, Stephens tuy thua thiệt Ostapenko về số điểm winner (6-25) nhưng chỉ mắc 21 lỗi đánh hỏng so với tận 48 lỗi từ Ostapenko.\r\n\r\nSet 1 chứng kiến hai tay vợt liên tiếp bẻ game của nhau mỗi người 4 lần trước khi Stephens thắng 7-5 khá nhọc nhằn trong loạt tie-break, có thời điểm dẫn 6-2 nhưng bị Ostapenko cứu 3 set point liên tiếp. Ở set 2, Stephens là người mất break trước nhưng Ostapenko xuống tinh thần và mắc rất nhiều sai lầm, từ đánh hỏng cho tới lỗi kép, và tay vợt người Mỹ giành thắng lợi 6-1 trong chỉ 35 phút, qua đó thắng chung cuộc 2-0 sau 1 giờ 33 phút thi đấu.\r\n\r\nChiến thắng này giúp Sloane Stephens giữ thành tích toàn thắng 6 trận trong trận chung kết các giải WTA, cũng như đoạt danh hiệu thứ 6 của cô trong sự nghiệp, trước đó đã đăng quang tại Washington Open, Auckland Open, Acapulco, Charleston Open và US Open.'),
(4, 'http://image.24h.com.vn/upload/1-2018/images/2018-03-31/Video-ket-qua-tennis-Del-Potro---John-Isner-Cang-thang-tie-break-bi-kich-den-som-d2-1522437864-973-width660height392.jpg', 'Del Potro - John Isner: Căng thẳng tie-break, bi kịch đến sớm (BK Miami Open)', 'Bị vắt kiệt sức trong trận gặp Raonic, Del Potro bất ngờ nhập cuộc với tâm lý khá uể oải trong cuộc đối đầu với tay vợt người Mỹ John Isner. Ở set đầu tiên, Potro nhanh chóng bị mất break trong game 2 và game 6, qua đó thua 1-6 chỉ sau vỏn vẹn 27 phút thi đấu.\r\n\r\nBước vào set 2, đương kim vô địch Indian Wells bắt đầu chơi tốt hơn và giằng co từng điểm số với Isner. Cuối cùng, cả hai tay vợt phải bước vào loạt tie-break để phân định thắng thua.\r\n\r\nĐiều đáng tiếc cho tay vợt Argentina là thể lực không đảm bảo đã khiến anh nhanh chóng bị \"Mr tie-break\" John Isner đè bẹp với tỷ số 7-2.\r\n\r\nThua chung cuộc sau 2 set, Del Potro đã khép lại hành trình tại giải đấu Miami Open 2018. Trong khi đó, John Isner bước tiếp vào chung kết gặp một trong hai đối thủ Carreno-Busta hoặc Zverev.'),
(5, 'http://image.24h.com.vn/upload/1-2018/images/2018-03-28/Vuot-Federer-Nadal-soan-ngoi-so-1-Hua-hen-nadal2-1522211656-639-width660height368.jpg', 'Vượt Federer, Nadal soán ngôi số 1: Hứa hẹn \"bung lụa\" ở giải đất nện', 'Bên cạnh đó, việc rút lui ở 2 giải Indian Wells và Miami còn khiến Nadal đối mặt với nguy cơ bị Federer nới rộng cách biệt trên bảng điểm ATP.\r\n\r\nThế nhưng, vận may lại mỉm cười với tay vợt người Tây Ban Nha sau khi “Tàu tốc hành” thi đấu không đạt kỳ vọng. Tay vợt Thụy Sĩ thất bại ở chung kết Indian Wells trước Juan Martin del Potro và thua Thanasi Kokkinakis ngay ở vòng hai Miami Mở rộng, dẫn đến việc mất tới 990 điểm ATP.\r\n\r\nĐiều này khiến tay vợt Thụy Sĩ bị tụt xuống vị trí thứ 2 và kém Nadal 100 điểm. Dự kiến, bảng xếp hạng ATP trong đầu tuần sau sẽ xác nhận “Ông vua” sân đất nện trở lại ngôi vị số 1.\r\n\r\nĐây rõ ràng là một \"bước đệm\" bất ngờ đối với Rafael Nadal trong kế hoạch trở lại trong thời gian tới. Nếu như bình phục hoàn toàn chấn thương và thi đấu thăng hoa trở lại, tay vợt người Tây Ban Nha sẽ có cơ hội bảo vệ số điểm 4.860 giành được năm ngoái khi vô địch Monte Carlo, Barcelona, Madrid và Roland Garros cùng với đó là thành tích vào tứ kết Rome Masters.\r\n\r\nNhưng điều này cũng đồng nghĩa với việc Nadal sẽ phải chiến đấu hết sức mình để bảo vệ các danh hiệu, nhằm tránh những mất điểm số không đáng có.\r\n\r\nMới đây, \"Tàu tốc hành\" người Thụy Sĩ đã quyết định không dự Roland Garros 2018 và bỏ toàn bộ các giải trên mặt sân đất nện. Đây chắc chắn là cơ hội không thể tuyệt vời hơn để Nadal vượt lên dẫn trước đối thủ. Sự kiện đầu tiên của mùa sân đất nện, Monte-Carlo Masters, sẽ diễn ra từ ngày 14/4 đến 22/4.\r\n\r\nHoặc trước đó, Nadal có thể cân nhắc tham dự Davis Cup được tổ chức tại Đức (6 đến 8/4). Theo chia sẻ của đội trưởng ĐT Tây Ban Nha, Sergi Bruguera cho biết sẽ chờ đến khi Nadal đưa ra quyết định chính thức. Lần cuối tay vợt 32 tuổi tham dự một giải đấu Davis Cup là vào hồi tháng 9/2016.'),
(6, 'http://image.24h.com.vn/upload/1-2018/images/2018-03-31/Chung-ket-Miami-Open-2018-Nu-hoang-Stephens-dau-nu-than-tie-break-mi3-1522471087-793-width660height440.jpg', 'Chung kết Miami Open 2018: Nữ hoàng mới Stephens đấu “nữ thần” tie-break', 'Nhìn lại hành trình tiến đến trận đấu tranh ngôi hậu đêm nay của Stephens, ngay cả những chuyên gia khó tính nhất cũng phải ngả mũ thán phục. Tay vợt sinh năm 1993 đã khuất phục liên tiếp 3 đàn chị từng giữ ngôi số 1 trên bảng xếp hạng WTA.\r\n\r\nCụ thể, Stephens đã hạ gục Muguruza ở vòng 4, tiếp đến là Kerber ở tứ kết và mới nhất là Azarenka. 3 trận thắng đó, tay vợt người Mỹ đã thể hiện tất cả những thế mạnh sở trường. Trước Muguruza và Kerber, Stephens bung sức tấn công quyết liệt. Đòn phủ đầu thành công khiến 2 đàn chị bị đánh gục hoàn toàn. Muguruza thua 3-6, 4-6 còn Kerber thảm hại hơn khi chỉ thắng được 3 game (1-6, 2-6).\r\n\r\nTrận chiến với Azarenka lại cho thấy Stephens đã trưởng thành và bản lĩnh như thế nào. Cô khởi đầu khó khăn và gác vợt khá dễ 3-6 trong set 1 trước kinh nghiệm của đàn chị người Belarus. Thế nhưng Stephens bừng tỉnh rất nhanh. Tay vợt người Bỉ thắng ngược thuyết phục 6-2, 6-1  ở 2 set sau đó để chấm dứt hy vọng của Azarenka.\r\n\r\nStephens đang tái hiện lại hình ảnh của chính mình tại US Open 2017. Giải Grand Slam vừa qua trên sân nhà, Stephens chơi bùng nổ và tiến thẳng một mạch đến ngôi vô địch. Đêm nay, Stephens đứng trước cơ hội đăng quang một lần nữa ở quê hương khi đối đầu Jelena Ostapenko.'),
(7, 'http://image.24h.com.vn/upload/1-2018/images/2018-03-31/a-zverev-660-1522458369-306-width660height458.jpg', 'A.Zverev - Carreno Busta: Khởi đầu kịch tính, trả giá sai lầm (BK Miami Open)', 'Trận bán kết giải Miami Open 2018 giữa Alexander Zverev và P. Carreno Busta diễn ra trong vòng gần 90 phút và mang đến cho khán giả những cảm xúc riêng biệt. Set thứ nhất diễn ra căng thẳng trong từng game đấu, hai tay vợt giữ vững được những lượt giao bóng và cần phải đến những loạt tie-break mới có thể định đoạt. Phần thắng cuối cùng nghiêng về A.Zverev, tay vợt được nhận định là có đẳng cấp cao hơn.\r\n\r\nSang đến set thứ hai, những người mong đợi một cuộc chiến giằng co khác đã phải thất vọng ra về. Tay vợt người Tây Ban Nha đã mất tinh thần sau khi để thua 4-7 trong loạt tie break ở set một  nên nhanh chóng mất 2 break-point trong set 2 và thúc thủ với tỉ số 2-6. \r\n\r\nChung cuộc, A.Zverev giành chiến thắng với tỉ số 2-0 (7-6, 6-2) và tiến vào chung kết Miami Open 2018. Đối thủ của anh trong trận chung kết là J. Isner, hạt giống số 14 của giải. Tay vợt người Mỹ bất ngờ vượt qua Del Potro cũng với tỉ số 2-0 (6-1, 7-6) ở trận bán kết còn lại.'),
(8, 'http://image.24h.com.vn/upload/1-2018/images/2018-03-30/Tin-the-thao-HOT-31-3-Federer-qua-hon-nguoi-roger-federer660-1522427211-840-width660height392.jpg', 'Tin thể thao HOT 31/3: Olympic 2020 nhận tin buồn từ Federer', 'Olympic 2020 nhận tin buồn từ Federer. Theo express.co, nhiều khả năng “Tàu tốc hành” sẽ không thể góp mặt ở Olympic 2020. Nguyên nhân nằm ở quyết định nghỉ thi đấu những tháng tới của Federer và anh sẽ không tham dự Davis Cup. Theo quy định, để góp mặt ở Olympic, các tay vợt phải dự Davis Cup 3/4 mùa gần nhất, trong khi FedEX đã không góp mặt ở giải này từ năm 2015.\r\n\r\nFederer quá hơn người. Theo express.co, cựu tay vợt người Pháp Nicolas Escude giờ là giám đốc giải Brest challenger cho biết, năm 1999 Federer đã từng vô địch giải này. Điều thú vị là sau rất nhiều năm gặp lại với vô số những trận chiến đã trải qua, 97 danh hiệu đã giành được, khi 2 người gặp lại Federer vẫn còn nhớ từng chi tiết của giải đấu năm đó. Escude cho biết Federer thậm chí không quên bất kỳ trận đấu nào của mình. Andy Murray chốt ngày trở lại. Tay vợt Anh quốc mới đây đã lên tiếng xác nhận việc góp mặt tại Libema Open - giải đấu diễn ra từ ngày 11 đến 17 tháng 6 tới đây ở Rosmalen (Hà Lan). Được biết, Murray chưa bao giờ tham dự giải đấu ATP 250 nào ở Rosmalen trong sự nghiệp.'),
(9, 'http://image.24h.com.vn/upload/1-2018/images/2018-03-25/Federer-thua-soc-o-Miami-Open-Nadal-bat-ngo-tro-lai-ngoi-so-1-the-gioi-15219303283147-1521942282-788-width660height371.jpg', 'Federer thua sốc ở Miami Open, Nadal bất ngờ trở lại ngôi số 1 thế giới', 'Chỉ trong vòng 1 tuần ngắn ngủi, Roger Federer đã phải nhận liên tiếp 3 cú sốc. Ở chung kết Indian Wells Masters, “Tàu tốc hành” bỏ lỡ đến 3 championship point và bị phế ngôi vô địch bởi Juan Martin Del Potro.\r\n\r\nĐến trận mở màn của mình ở Miami Open rạng sáng nay, dù cũng là ĐKVĐ như tại Indian Wells nhưng Federer lại gây thất vọng cực lớn khi thua ngược tay vợt mới 21 tuổi người Úc xếp hạng 175 thế giới Thanasi Kokkinakis 6-3, 3-6, 6-7 (4-7) ngay trận mở màn của FedEx ở vòng 2. Như vậy, Federer đã không hoàn thành nhiệm vụ ít nhất lọt vào tứ kết giải Masters 1000 thứ 2 trong năm và anh đã bị Rafael Nadal đòi lại ngôi số 1 thế giới chỉ 45 ngày sau khi giành được nó từ giải ATP 500 Rotterdam Open.\r\n\r\nPhát biểu sau trận đấu đáng quên với Kokkinakis vừa qua ở Miami, huyền thoại sống 36 tuổi người Thụy Sĩ thất vọng đến nỗi chẳng hiểu sao mình có thể thua đau đến vậy, đặc biệt là ở loạt tie-break set 3, y như cách anh gác vợt trước Del Potro tại Indian Wells:\r\n\r\n“Thật đáng thất vọng. Tôi cũng chẳng biết tại sao mình có thể đánh với mức độ như vậy hôm nay. Thỉnh thoảng bạn phải có những trận đấu tệ như vậy và phải tìm cách vượt qua chúng. Tôi đã không làm được điều đó vào hôm nay.'),
(10, 'http://image.24h.com.vn/upload/1-2018/images/2018-03-30/Cap-nhat-Miami-Open-ngay-9-tt-1522363119-796-width660height458.jpg', 'Miami Open ngày 9: \"Đấu súng\" nghẹt thở, á quân US Open thua đau', 'Dù được đánh giá cao hơn đối thủ Pablo Carreno-Busta nhưng hạt giống số 6 người Nam Phi Kevin Anderson đã thua 4-6 trong set 1 trận tứ kết đơn nam Miami Open năm nay.\r\n\r\nSang set 2, tay vợt hạt giống số 16 người Tây Ban Nha Carreno-Busta đã dẫn 5-4 và có 2 match-point ở game thứ 10 khi giao bóng và dẫn điểm 40-15. Thế nhưng, anh đã để Anderson bất ngờ đòi break trước khi mất thêm 1 game giao bóng và thua ngược 5-7 trong set này.\r\n\r\nBước vào set 3, kịch tính dâng cao khi họ phải kéo nhau vào loạt tie-break để phân thắng - bại. Ở màn đấu súng này, Anderson có 1 macth point trước nhưng không tận dụng được và sau đó phải trả giá đắt khi thua điểm 6-8 trước đối thủ đến từ xứ sở đấu bò. Thắng nhọc nhằn sau 2 giờ 41 phút, Carreno-Busta tiến vào bán kết Miami Masters năm nay, nơi anh sẽ gặp người thắng trong cặp đấu giữa hạt giống số 4 người Đức Alexander Zverev và hạt giống số 29 người Croatia Borna Coric.');

-- --------------------------------------------------------

--
-- Table structure for table `baiviettrangchu`
--

CREATE TABLE `baiviettrangchu` (
  `id` int(10) UNSIGNED NOT NULL,
  `anh` varchar(200) COLLATE utf8_unicode_ci NOT NULL,
  `tieude` varchar(200) COLLATE utf8_unicode_ci NOT NULL,
  `noidung` text COLLATE utf8_unicode_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
-- Dumping data for table `baiviettrangchu`
--

INSERT INTO `baiviettrangchu` (`id`, `anh`, `tieude`, `noidung`) VALUES
(1, 'http://image.24h.com.vn/upload/2-2018/images/2018-04-01/Thanh-Hoa---SLNA-Ban-pha-khong-ngung-untitled-2-1522583967-610-width660height377.jpg', 'Thanh Hóa - SLNA: Bắn phá không ngừng, bỏ túi 3 điểm', 'Thanh Hóa và SLNA quá hiểu nhau nên họ nhập cuộc chậm rãi. Sau 5 phút đầu, cả hai bắt đầu tạo ra những tình huống đáng chú ý. Khắc Ngọc chuyền dài tốt nhưng đồng đội xử lý vụng trong vòng cấm Thanh Hóa. Pape Omar đáp trả bằng cú dứt điểm từ ngoài vòng cấm, bóng đi vọt xà. Thế trận sau đây dần nghiêng về Thanh Hóa. Phút 23, Hoàng Văn Bình đá phạt cực hóc hiểm nhưng thủ thành Vũ Hải vẫn kịp bay người cản phá. Phút 29 và 35, Vũ Hãi tiếp tục thể hiện sự tập trung bằng những pha bắt bóng tốt, cứu cho SLNA khỏi nhận bàn thua.\r\n\r\nĐầu hiệp 2, Phan Văn Đức suýt đưa SLNA vượt lên nếu cú ra chân của anh trong vòng cấm không bị đồng đội ở tuyển U23, thủ thành Tiến Dũng kịp dùng chân cứu thua. Thanh Hóa dồn lực tấn công. Ofere sau cú đá không thắng được Vũ Hải, đánh đầu hóc hiểm mở tỷ số phút 55.\r\n\r\nThời gian còn lại, SLNA đẩy cao đội hình, Thanh Hóa có vô số cơ hội phản công nhưng đều lãng phí. Dù vậy chiến thắng này cũng giúp đội bóng xứ Thanh bỏ túi 3 điểm trọn vẹn.'),
(2, 'http://image.24h.com.vn/upload/1-2018/images/2018-03-20/Tuan-Anh-chan-thuong-Xuan-Truong-oan-minh-ganh-tuyen-giua-HAGL-29343111_16964346104-1521544498-198-width660height440.jpg', 'Tuấn Anh chấn thương: Xuân Trường “oằn mình” gánh tuyến giữa HAGL', 'Trong lứa “gà nòi” đầu tiên của bầu Đức ở Học viện bóng đá HAGL - JMG, tiền vệ Nguyễn Tuấn Anh được đánh giá là có tiềm năng lớn nhất. Nhãn quan chiến thuật sắc bén, kỹ thuật cực tốt, lối chơi cơ bản và hiện đại, đặc biệt là rất mạnh trong những cú sút xa, chàng tiền vệ người Thái Bình hứa hẹn sẽ vươn tầm ngôi sao trong tương lai. Song hành với Tuấn Anh là một Lương Xuân Trường bền bỉ, có sức chiến đấu cao cùng tố chất của một thủ lĩnh đích thực. Sự ăn ý của Xuân Trường và Tuấn Anh được thể hiện ở những giải đấu trẻ. Thời điểm ấy, giới mộ điệu mơ về một cặp tiền vệ trung tâm trong mơ, không chỉ của HAGL mà còn của cả nền bóng đá Việt Nam. Xuân Trường và Tuấn Anh mang trong mình hoài bão của NHM về một cuộc lật đổ đối với “ông kẹ” Thái Lan. Chúng ta hy vọng cặp tiền vệ trung tâm tài hoa này sẽ giúp Việt Nam chơi sòng phẳng, mạch lạc với đối thủ kỵ giơ.\r\n\r\nNhưng rồi những chấn thương cứ bám riết lấy Tuấn Anh. 3 năm qua, kể từ lần đầu lên chơi tại V-League, thời gian Tuấn Anh ra sân ít hơn trên giường bệnh. Ngay cả chuyến “du học” Nhật Bản trong màu áo  Yokohama FC cũng không giúp tiền vệ người Thái Bình vượt qua được vận đen của số phận. Chấn thương có thể khiến Tuấn Anh nghỉ dài hạn trong trận đấu với Hải Phòng vừa qua là một cú đánh mạnh vào nỗ lực vượt qua số phận của chàng “Nhô”.\r\n\r\n\r\nNhưng chấn thương của Tuấn Anh không chỉ ảnh hưởng đến bản thân cầu thủ này, mà Hoàng Anh Gia Lai cũng thiếu hụt một nhân tố trụ cột, còn cá nhân Xuân Trường mất đi một đối tác ăn ý ở khu trung tuyến. Phút 22, sau khi Tuấn Anh rời sân, HLV Dương Minh Ninh của HAGL tung Triệu Việt Hưng vào thay thế. Bộ đôi này có màn kết hợp không hề tệ, riêng Xuân Trường lập siêu phẩm đá phạt để giúp HAGL ra về với 1 điểm.\r\n\r\nThế nhưng, nhìn vào cả một chặng đường dài tại V-League 2018, sự vá víu này chắc chắn sẽ ảnh hưởng đến HAGL nói chung và cá nhân Xuân Trường nói riêng. Triệu Việt Hưng chỉ kém Tuấn Anh 1 tuổi, nhưng kinh nghiệm thi đấu chắc chắn thua xa, và khả năng kết hợp với Xuân Trường cũng là điều đáng bàn. Một cầu thủ khác có thể trám chỗ của Tuấn Anh ở khu trung tuyến HAGL, đó là Châu Ngọc Quang. Dù vậy, Châu Ngọc Quang cũng giống Triệu Việt Hưng, khó có thể khỏa lấp lỗ hổng nơi tuyến giữa đội bóng phố Núi.'),
(3, 'http://image.24h.com.vn/upload/2-2018/images/2018-04-01/harry-kane-injury-660-1522546113-449-width660height495.jpg', 'Harry Kane \"liều lĩnh\" đấu Chelsea: Dễ tàn giấc mơ World Cup', 'Tháng trước, tiền đạo người Anh dính chấn thương dây chằng mắt cá sau một pha va chạm với thủ thành Begovic trong chiến thắng 4-1 của Tottenham trước Bournemouth. Sau những buổi kiểm tra kỹ càng, các bác sĩ đưa ra kết luận rằng Harry Kane phải cần ít nhất một tháng để hồi phục.\r\n\r\nĐiều này không quá mới với giới mộ điệu bởi cùng thời gian này năm ngoái, tiền đạo của Tottenham cũng dính chấn thương tương tự và cũng phải mất hơn 4 tuần mới có thể trở lại thi đấu.\r\n\r\nTuy nhiên, theo thông tin mới nhất từ CLB Tottenham thì HLV Pochettino quyết định điền tên Harry Kane trong chuyến làm khách của Chelsea vào cuối tuần này (22h, 1/4), sớm hơn một tuần so với dự kiến của bác sĩ. Vẫn biết đây là một trận đấu có tính chất quan trọng nhưng nếu ông thực sự đưa tiền đạo người Anh vào sân thì đây có thể coi là một quyết định cực kỳ liều lĩnh của ông thầy người Argentina.\r\n\r\nNên nhớ, mùa trước HLV Pochettino không dám dùng Kane mà chỉ đưa anh vào sân ở những phút cuối khi trận đấu đã an bài. Đó là một nước đi đúng đắn bởi tiền đạo này đã \"nổ súng\" ngay ở trận tiếp theo. Kinh nghiệm là có nhưng liệu Pochettino có đủ tỉnh táo để quyết định bởi Tottenham rất cần Kane trong trận đấu này.\r\n\r\nTrận derby Tây Bắc thành London chắc chắn sẽ là một cuộc chiến không khoan nhượng với nhiều pha bóng “rắn” tới từ cả hai bên. Harry Kane thực sự ra sân thì va chạm là điều khó tránh khỏi.\r\n\r\nNếu chẳng may tiền đạo này dính thêm một chấn thương, đó sẽ là thảm họa không chỉ cho Tottenham ở cuối mùa giải mà còn là nỗi khốn khổ của người Anh bởi World Cup 2018 đã tới rất gần.'),
(4, 'http://image.24h.com.vn/upload/2-2018/images/2018-04-01/Video-ket-qua-bong-da-Juventus---AC-Milan-j2-1522529663-980-width660height367.jpg', 'Juventus - AC Milan: Đại chiến cân não, 8 phút định đoạt', 'Bước vào cuộc đối đầu trước đối thủ truyền kiếp AC Milan, đoàn quân của Allegri khao khao giành chiến thắng nhằm tạo đà tâm lý trước cuộc tiếp đón Real tại Champions League. Ngay ở phút thứ 8, các CĐV trên sân Juventus đã được ăn mừng sau pha dứt điểm tuyệt hảo của Dybala trước vòng cấm. Tuy nhiên, lợi thế dẫn bàn của đội chủ nhà đã bị \"người cũ\" Bonucci san lấp ở phút 28 với một cú đánh đầu cận thành.\r\n\r\nBước sang hiệp 2, Milan có hàng loạt cơ hội ghi bàn để lội ngược dòng nhưng lại phung phí. Phút 79, Cuadrado trừng phạt đội khách với cú đánh đầu chéo góc. Và chỉ 8 phút sau, số phận trận đấu được định đoạt sau khi Khedira dứt điểm chính xác sau pha phối hợp đẹp mắt bên cánh trái của Juventus.\r\n\r\nVới chiến thắng đầy bản lĩnh trước Milan, Juventus tiếp tục ngự trị trên đỉnh BXH với 78 điểm, nhiều hơn đội xếp thứ 2 Napoli 4 điểm. Trong khi đó, đội bóng của Gattuso giậm chân tại chỗ với 50 điểm ở vị trí thứ 6 dù vẫn còn 1 trận chưa đấu.'),
(5, 'http://image.24h.com.vn/upload/2-2018/images/2018-04-01/Chung-ket-Miami-Open-2018-Hoang-tu-Zverev-doi-khoanh-khac-xung-vuong-mi2-1522553790-328-width660height371.jpg', 'Chung kết Miami Open 2018: “Hoàng tử” Zverev đợi khoảnh khắc xưng vương', 'Kịch bản trận chung kết trong mơ đã không thành sự thật khi Del Potro bị loại tại bán kết. Thế nhưng John Isner đã chứng minh anh xứng đáng hơn nhà vô địch Indian Wells với chiến thắng quá thuyết phục 6-1, 7-6(2) để trở thành đối thủ của Alexander Zverev. Sau trận ra quân phải mất đến 3 set để giải quyết Jiri Vesely, liên tiếp những trận sau đó John Isner luôn biết cách bắn hạ đối thủ nhanh gọn và không thua thêm 1 set đấu nào. Đây là thành tích đầy bất ngờ của tay vợt 32 tuổi nước chủ nhà khi biết rằng chướng ngại vật anh phải đối đầu gồm toàn “hàng khủng” như Marin Cilic, Hyeon Chung và Del Potro.\r\n\r\nViệc liên tiếp có được những thắng lợi thuyết phục trở thành động lực rất lớn cho John Isner phục thù đàn em kém 12 tuổi. Trong quá khứ, Isner chưa từng một lần được nếm trải cảm giác chiến thắng trước Zverev.\r\n\r\nCụ thể, hai tay vợt đã có 3 lần chạm trán nhưng Zverev toàn thắng. Lần đầu tiên năm 2016 tại Thượng Hải Masters, khi đó Isner thua đậm 4-6, 2-6 ngay vòng đầu tiên. Tại Miami Open năm ngoái, tay vợt chủ nhà tiếp tục ôm hận ở vòng 2 sau 3 loạt tie-break siêu căng thẳng. Đến Rome Masters 2017, Zverev có trận thắng thứ 3 trước đàn em khi đụng độ nhau tại bán kết.\r\n\r\nChặng đường đến trận chung kết của Zverev không hề bằng phẳng. Tay vợt trẻ người Đức đã trải qua rất nhiều thử thách và không ít trận đấu cam go giằng co 3 set. Ngay vòng đầu tiên, Zverev đã suýt nếm trái đắng trước Daniil Medvedev và chỉ thoát hiểm sau loạt tie-break đầy căng thẳng set 3 với tỷ số 7-5.'),
(6, 'http://image.24h.com.vn/upload/1-2018/images/2018-03-31/Chung-ket-Miami-Open-2018-Nu-hoang-Stephens-dau-nu-than-tie-break-mi4-1522471087-85-width660height483.jpg', 'Chung kết Miami Open 2018: Nữ hoàng mới Stephens đấu “nữ thần” tie-break', 'Giống với Indian Wells 2018, Miami Open cũng chứng kiến rất nhiều bất ngờ đến từ những tay vợt trẻ. Ở nội dung đơn nữ, hiện tượng Naomi Osaka đã bị giải mã nhưng Sloane Stephens lại bất ngờ trở lại. Hiện tượng tại US Open 2017 đưa người hâm mộ đi hết từ ngạc nhiên này đến cú sốc khác để ghi danh vào chung kết. Nhìn lại hành trình tiến đến trận đấu tranh ngôi hậu đêm nay của Stephens, ngay cả những chuyên gia khó tính nhất cũng phải ngả mũ thán phục. Tay vợt sinh năm 1993 đã khuất phục liên tiếp 3 đàn chị từng giữ ngôi số 1 trên bảng xếp hạng WTA.\r\n\r\nCụ thể, Stephens đã hạ gục Muguruza ở vòng 4, tiếp đến là Kerber ở tứ kết và mới nhất là Azarenka. 3 trận thắng đó, tay vợt người Mỹ đã thể hiện tất cả những thế mạnh sở trường. Trước Muguruza và Kerber, Stephens bung sức tấn công quyết liệt. Đòn phủ đầu thành công khiến 2 đàn chị bị đánh gục hoàn toàn. Muguruza thua 3-6, 4-6 còn Kerber thảm hại hơn khi chỉ thắng được 3 game (1-6, 2-6).\r\n\r\nTrận chiến với Azarenka lại cho thấy Stephens đã trưởng thành và bản lĩnh như thế nào. Cô khởi đầu khó khăn và gác vợt khá dễ 3-6 trong set 1 trước kinh nghiệm của đàn chị người Belarus. Thế nhưng Stephens bừng tỉnh rất nhanh. Tay vợt người Bỉ thắng ngược thuyết phục 6-2, 6-1  ở 2 set sau đó để chấm dứt hy vọng của Azarenka.\r\n\r\nStephens đang tái hiện lại hình ảnh của chính mình tại US Open 2017. Giải Grand Slam vừa qua trên sân nhà, Stephens chơi bùng nổ và tiến thẳng một mạch đến ngôi vô địch. Đêm nay, Stephens đứng trước cơ hội đăng quang một lần nữa ở quê hương khi đối đầu Jelena Ostapenko.'),
(7, 'http://image.24h.com.vn/upload/2-2018/images/2018-04-01/man-city-660-1522549712-957-width660height495.jpg', 'Pep - Man City vô đối Ngoại hạng Anh: 8 kỷ lục sắp bị chinh phục', 'Man City giành chiến thắng, đó là điệp khúc mà người hâm mộ Ngoại hạng Anh nghe đã quen trong mùa giải này. Everton là nạn nhân mới nhất của họ dù được thi đấu trên sân nhà. Leroy Sane mở tỉ số với cú volley cận thành, sau đó Gabriel Jesus cùng Sterling lần lượt nâng tỉ số lên thành 3-0 trước khi Bolasie ghi bàn danh dự cho chủ nhà ở trong hiệp hai.Một vài ý kiến cho rằng nếu Pep Guardiola không lo ngại trận lượt đi với Liverpool tại tứ kết Champions League sắp tới thì có lẽ tỉ số của trận đấu đã đậm đà hơn nhiều.\r\n\r\n Với chiến thắng này, \"The Citizens\" đã gần như vô địch Ngoại hạng Anh 2017/18. Họ vẫn giữ được khoảng cách 16 điểm so với đội đứng thứ hai là MU trong khi giải đấu chỉ còn 7 vòng đấu nữa là kết thúc. Nếu giữ vững phong độ như thời điểm hiện tại, rất có thể Man City sẽ vô địch sớm ít nhất 5 vòng đấu.\r\n\r\nSau khi chi tiêu không tiếc tay trong hai kỳ chuyển nhượng vừa qua, Pep Guardiola đã có trong tay một đội hình khá ưng ý và ông đang chuẩn bị cùng Man City phá tới 8 kỷ lục của Ngoại hạng Anh chỉ trong một mùa giải. Nếu Man City có thể phá đủ những kỷ lục trên thì Chelsea là đội thiệt hại nhiều nhất khi họ đang nắm tới 6/8 kỷ lục nói trên. Kỷ lục có niên hạn lâu nhất thuộc về MU lập nên ở mùa 1999/2000 trong khi kỷ lục có niên hạn mới nhất là của Chelsea vừa lập ở mùa giải trước.\r\n\r\nMan City còn 7 trận đấu nữa tại Ngoại hạng Anh 2017/18 trong đó có 4 trận sân nhà và 3 trận sân khách. Thầy trò của Pep Guardiola có thể xô đổ ngay kỷ lục của MU nếu như thắng chính \"Quỷ đỏ\" trong trận derby Manchester ở vòng đấu tới.'),
(8, 'http://image.24h.com.vn/upload/2-2018/images/2018-04-01/Nhan-dinh-bong-da-Arsenal---Stoke-City-40vong-32-Ngoai-hang-Anh41-gettyimages-1522520732-219-width660height346.jpg', 'Arsenal - Stoke City: \"Thần thái\" ông lớn, quyết vùi dập \"nhược tiểu\"', 'Sau chuỗi 4 thất bại liên tiếp trên mọi đấu trường, Arsenal dần bắt đầu lấy lại phong độ với 3 chiến thắng liên tiếp. Hàng công ghi tới 8 bàn trong quãng thời gian này, đặc biệt bộ đôi tân binh Mkhitaryan - Aubameyang cũng ngày càng cho thấy sự ăn ý. Tất nhiên, NHM Arsenal và HLV Arsene Wenger vẫn phải chấp nhận thực tế phũ phàng: Với vị trí thứ thứ 6 trên BXH (48 điểm/30 trận), kém top 4 tới… 13 điểm, cơ hội giành vé dự Champions League theo “cửa” chính thống của họ gần như không thể.\r\n\r\nChính vì vậy, thầy trò Wenger chỉ còn cách dồn toàn bộ tâm sức cho đấu trường Europa League – nơi họ đang tràn đầy hưng phấn sau khi đánh bại AC Milan (5-1 sau 2 lượt trận) ở vòng 1/32. 8 trận đấu cuối cùng của Premier League, họ vẫn sẽ chiến đấu cho danh dự của một \"ông lớn\" cũng như bảo toàn vị trí hiện tại.\r\n\r\nNếu Arsenal là nỗi thất vọng ở nửa trên BXH, thì Stoke City cũng là \"đại diện\" tiêu biểu cho những CLB thuộc tốp cuối với vị trí thứ 19 (27 điểm/31 trận), kém nhóm trụ hạng tới 4 điểm. Phân tích sâu hơn về thành tích để thấy được sự kém cỏi của thầy trò Paul Lambert: 6 chiến thắng/31 trận mùa này, 1 chiến thắng/15 trận sân khách. 5 chuyến hành quân xa nhà gần nhất, Stoke chưa thể ca khúc khải hoàn (hòa 2, thua 3). Xét về thành tích đối đầu, Arsenal hoàn toàn áp đảo Stoke (thắng 12/21 trận, hòa 3 trận). Lịch sử cũng chỉ ra, \"The Potters\" chưa bao giờ đánh bại đối thủ 2 trận liên tiếp kể từ mùa... 1975/76, trong khi họ đã \"lỡ\" thắng ở trận lượt đi mùa này!\r\n\r\nLịch thi đấu sắp tới của Stoke trong những vòng tới cực kì khó nhọc (lần lượt gặp Tottenham tuần tới và Liverpool 3 vòng sau đó). Nếu thất bại trên sân Arsenal, cánh cửa xuống Championship sẽ ngày càng rộng mở với thầy trò Paul Lambert. ');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `baiviet`
--
ALTER TABLE `baiviet`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `baivietanh`
--
ALTER TABLE `baivietanh`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `baivietbongro`
--
ALTER TABLE `baivietbongro`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `baiviethot`
--
ALTER TABLE `baiviethot`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `baiviettennis`
--
ALTER TABLE `baiviettennis`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `baiviettrangchu`
--
ALTER TABLE `baiviettrangchu`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `baiviet`
--
ALTER TABLE `baiviet`
  MODIFY `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=11;

--
-- AUTO_INCREMENT for table `baivietanh`
--
ALTER TABLE `baivietanh`
  MODIFY `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=11;

--
-- AUTO_INCREMENT for table `baivietbongro`
--
ALTER TABLE `baivietbongro`
  MODIFY `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=11;

--
-- AUTO_INCREMENT for table `baiviethot`
--
ALTER TABLE `baiviethot`
  MODIFY `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=4;

--
-- AUTO_INCREMENT for table `baiviettennis`
--
ALTER TABLE `baiviettennis`
  MODIFY `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=11;

--
-- AUTO_INCREMENT for table `baiviettrangchu`
--
ALTER TABLE `baiviettrangchu`
  MODIFY `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=9;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
